PRIMARY_COLOR   = "#0F90DB" 
SECONDARY_COLOR = "#1565C0"  
TERTIARY_COLOR  = "#1E88E5" 
QUATERNARY_COLOR = "#42A5F5"
QUINARY_COLOR   = "#90CAF9" 
SENARY_COLOR    = "#E3F2FD"

SCALE_COLOR_MAP = 'Blues'

CATEGORIES_COLORS = [
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    TERTIARY_COLOR,
    QUATERNARY_COLOR,
    QUINARY_COLOR,
    SENARY_COLOR
]